[program:cobblerd]
command=/usr/local/bin/cobblerd -F
autostart=true
autorestart=true
stdout_logfile=/var/log/cobblerd-stdout.log
stderr_logfile=/var/log/cobblerd-stderr.log

[program:apache2]
command=/usr/sbin/apache2ctl -DFOREGROUND
autostart=true
autorestart=true
startretries=10
startsecs=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
