[program:cobblerd]
command=/usr/bin/cobblerd -F
autostart=true
autorestart=true
stdout_logfile=/var/log/cobblerd-stdout.log
stderr_logfile=/var/log/cobblerd-stderr.log

[program:httpd]
command=/usr/sbin/httpd -D FOREGROUND
autostart=true
autorestart=true
stdout_logfile=/var/log/httpd-stdout.log
stderr_logfile=/var/log/httpd-stderr.log
