[program:cobblerd]
command=/usr/bin/cobblerd -F
autostart=true
autorestart=true
stdout_logfile=/var/log/cobblerd-stdout.log
stderr_logfile=/var/log/cobblerd-stderr.log

[program:httpd]
command=/usr/sbin/httpd -DFOREGROUND -E /dev/stderr
autostart=true
autorestart=true
startretries=10
startsecs=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
